package com.example.newsandlearn.Fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;

import com.example.newsandlearn.Adapter.DailyTaskAdapter;
import com.example.newsandlearn.Model.DailyTask;
import com.example.newsandlearn.R;
import com.example.newsandlearn.Utils.ProgressManager;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/**
 * DailyTasksFragment - Displays daily tasks from Firebase
 * Tasks are auto-generated by ProgressManager, NO hard-coded data
 */
public class DailyTasksFragment extends Fragment {

    private static final String TAG = "DailyTasksFragment";

    // UI Components
    private SwipeRefreshLayout swipeRefresh;
    private RecyclerView tasksRecyclerView;
    private ProgressBar loadingIndicator, overallProgress;
    private LinearLayout emptyState;
    private TextView dateText, tasksCompletedText, xpRewardText;

    // Data
    private List<DailyTask> taskList;
    private DailyTaskAdapter adapter;

    // Services
    private ProgressManager progressManager;

    public DailyTasksFragment() {
        // Required empty constructor
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_daily_tasks, container, false);

        initializeServices();
        initializeViews(view);
        setupRecyclerView();
        setupListeners();
        loadTodaysTasks();

        return view;
    }

    private void initializeServices() {
        progressManager = ProgressManager.getInstance();
        taskList = new ArrayList<>();
    }

    private void initializeViews(View view) {
        // Header
        dateText = view.findViewById(R.id.date_text);
        tasksCompletedText = view.findViewById(R.id.tasks_completed_text);
        overallProgress = view.findViewById(R.id.overall_progress);
        xpRewardText = view.findViewById(R.id.xp_reward_text);

        // List
        swipeRefresh = view.findViewById(R.id.swipe_refresh);
        tasksRecyclerView = view.findViewById(R.id.tasks_recycler_view);
        loadingIndicator = view.findViewById(R.id.loading_indicator);
        emptyState = view.findViewById(R.id.empty_state);

        // Set today's date
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM d", Locale.getDefault());
        dateText.setText(dateFormat.format(new Date()));
    }

    private void setupRecyclerView() {
        tasksRecyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        adapter = new DailyTaskAdapter(getContext(), taskList);
        tasksRecyclerView.setAdapter(adapter);
    }

    private void setupListeners() {
        swipeRefresh.setOnRefreshListener(this::loadTodaysTasks);
    }

    /**
     * Load today's tasks from Firebase via ProgressManager
     * Tasks are auto-generated, NOT hard-coded
     */
    private void loadTodaysTasks() {
        showLoading(true);

        progressManager.getTodaysTasks(new ProgressManager.TaskCallback() {
            @Override
            public void onSuccess(List<DailyTask> tasks) {
                taskList.clear();
                if (tasks != null) {
                    taskList.addAll(tasks);
                }

                adapter.notifyDataSetChanged();
                updateProgress();
                showLoading(false);
                swipeRefresh.setRefreshing(false);

                if (isAllTasksCompleted()) {
                    showEmptyState();
                } else {
                    hideEmptyState();
                }
            }

            @Override
            public void onFailure(Exception e) {
                showLoading(false);
                swipeRefresh.setRefreshing(false);
                // Show error or empty state
            }
        });
    }

    private void updateProgress() {
        int totalTasks = taskList.size();
        int completedTasks = 0;
        int totalXP = 0;

        for (DailyTask task : taskList) {
            if (task.isCompleted()) {
                completedTasks++;
            }
            totalXP += task.getXpReward();
        }

        // Update stats
        tasksCompletedText.setText(completedTasks + "/" + totalTasks);

        // Update progress bar
        if (totalTasks > 0) {
            int progress = (completedTasks * 100) / totalTasks;
            overallProgress.setProgress(progress);
        }

        // Update XP text
        if (completedTasks == totalTasks) {
            xpRewardText.setText("All tasks completed! +" + totalXP + " XP earned");
            xpRewardText.setTextColor(getResources().getColor(R.color.success, null));
        } else {
            int remainingXP = totalXP;
            for (DailyTask task : taskList) {
                if (task.isCompleted()) {
                    remainingXP -= task.getXpReward();
                }
            }
            xpRewardText.setText("Complete all to earn " + totalXP + " XP");
        }
    }

    private boolean isAllTasksCompleted() {
        if (taskList.isEmpty()) return false;
        
        for (DailyTask task : taskList) {
            if (!task.isCompleted()) {
                return false;
            }
        }
        return true;
    }

    private void showLoading(boolean show) {
        if (show) {
            loadingIndicator.setVisibility(View.VISIBLE);
            tasksRecyclerView.setVisibility(View.GONE);
            emptyState.setVisibility(View.GONE);
        } else {
            loadingIndicator.setVisibility(View.GONE);
        }
    }

    private void showEmptyState() {
        emptyState.setVisibility(View.VISIBLE);
        tasksRecyclerView.setVisibility(View.GONE);
    }

    private void hideEmptyState() {
        emptyState.setVisibility(View.GONE);
        tasksRecyclerView.setVisibility(View.VISIBLE);
    }

    @Override
    public void onResume() {
        super.onResume();
        // Refresh when returning
        loadTodaysTasks();
    }
}
